#!/usr/bin/env bash
# deploy-client.sh — deploy one customer's site to THEIR Cloudflare account.
#
# Usage:
#   ./scripts/deploy-client.sh --token CF_TOKEN --domain example.ir \
#       --admin-password 'S3cret!' [--worker NAME] [--db NAME] [--skip-dns] \
#       [--changelog-url URL] [--deploy-hook-url URL]
#
# What it does:
#   1. Validates inputs + verifies the token (whoami).
#   2. Creates (or reuses) a D1 database for this customer.
#   3. Writes a per-client wrangler.<worker>.toml (project wrangler.toml untouched).
#   4. Deploys the Worker (OpenNext build runs via wrangler [build] command).
#   5. Ensures apex A + www CNAME records exist (proxied) unless --skip-dns.
#   6. Smoke-tests the workers.dev URL and prints a delivery summary.
#
# Notes:
#   - Never commit a token. Pass it via --token or CLOUDFLARE_API_TOKEN env.
#   - Bash + node + npx wrangler required. Run from the project root.
set -euo pipefail

TOKEN="${CLOUDFLARE_API_TOKEN:-}"
DOMAIN=""
ADMIN_PASSWORD=""
WORKER=""
DB=""
SKIP_DNS=0
CHANGELOG_URL=""
DEPLOY_HOOK_URL=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --token) TOKEN="$2"; shift 2 ;;
    --domain) DOMAIN="$2"; shift 2 ;;
    --admin-password) ADMIN_PASSWORD="$2"; shift 2 ;;
    --worker) WORKER="$2"; shift 2 ;;
    --db) DB="$2"; shift 2 ;;
    --changelog-url) CHANGELOG_URL="$2"; shift 2 ;;
    --deploy-hook-url) DEPLOY_HOOK_URL="$2"; shift 2 ;;
    --skip-dns) SKIP_DNS=1; shift ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

[[ -z "$TOKEN" ]] && { echo "ERROR: --token (or CLOUDFLARE_API_TOKEN) is required." >&2; exit 1; }
[[ -z "$DOMAIN" ]] && { echo "ERROR: --domain is required (e.g. gheshlaghi.ir)." >&2; exit 1; }
[[ -z "$ADMIN_PASSWORD" ]] && { echo "ERROR: --admin-password is required." >&2; exit 1; }
(( ${#ADMIN_PASSWORD} < 8 )) && { echo "ERROR: admin password must be >= 8 chars." >&2; exit 1; }

SLUG="$(echo "$DOMAIN" | sed 's/\.[^.]*$//' | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '-')"
WORKER="${WORKER:-manager-${SLUG}}"
DB="${DB:-manager_$(echo "$SLUG" | tr '-' '_')_db}"

export CLOUDFLARE_API_TOKEN="$TOKEN"
W="node ./node_modules/wrangler/bin/wrangler.js"

echo "==> 1/6 verifying token…"
ACCOUNT_ID="$($W whoami 2>/dev/null | grep -a -oE '[0-9a-f]{32}' | head -1)"
[[ -z "$ACCOUNT_ID" ]] && { echo "ERROR: token invalid or cannot list accounts. Check the token permissions." >&2; exit 1; }
export CLOUDFLARE_ACCOUNT_ID="$ACCOUNT_ID"
echo "    account: $ACCOUNT_ID"

echo "==> 2/6 ensuring D1 database '$DB'…"
DB_ID="$($W d1 list 2>/dev/null | grep -a -E "\| $DB " | grep -a -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1 || true)"
if [[ -z "$DB_ID" ]]; then
  DB_ID="$($W d1 create "$DB" 2>&1 | grep -a -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1)"
  [[ -z "$DB_ID" ]] && { echo "ERROR: could not create D1 database '$DB'." >&2; exit 1; }
  echo "    created: $DB_ID"
else
  echo "    reused:  $DB_ID"
fi

echo "==> 3/6 writing per-client config wrangler.${WORKER}.toml…"
SESSION_SECRET="$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")"
APP_VERSION="$(node -p "require('./package.json').version")"
UPDATE_VARS=""
[[ -n "$CHANGELOG_URL" ]] && UPDATE_VARS="${UPDATE_VARS}
UPDATE_CHANGELOG_URL = \"$CHANGELOG_URL\""
[[ -n "$DEPLOY_HOOK_URL" ]] && UPDATE_VARS="${UPDATE_VARS}
UPDATE_DEPLOY_HOOK_URL = \"$DEPLOY_HOOK_URL\""
# releases.json must exist at build time — it is bundled into every install.
(npm run changelog >/dev/null 2>&1 || true)
cat > "wrangler.${WORKER}.toml" <<EOF
# Auto-generated by scripts/deploy-client.sh for $DOMAIN — do not commit.
name = "$WORKER"
main = ".open-next/worker.js"
compatibility_date = "2025-08-16"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
DEMO_MODE = "false"
SESSION_SECRET = "$SESSION_SECRET"
ADMIN_PASSWORD = "$ADMIN_PASSWORD"
APP_VERSION = "$APP_VERSION"$UPDATE_VARS

[[d1_databases]]
binding = "DB"
database_name = "$DB"
database_id = "$DB_ID"

[[routes]]
pattern = "$DOMAIN/*"
zone_name = "$DOMAIN"

[[routes]]
pattern = "www.$DOMAIN/*"
zone_name = "$DOMAIN"

[build]
command = "npx @opennextjs/cloudflare build"
EOF

echo "==> 4/6 deploying worker '$WORKER'… (takes a few minutes)"
$W deploy --config "wrangler.${WORKER}.toml" 2>&1 | tail -8

if [[ "$SKIP_DNS" -eq 0 ]]; then
  echo "==> 5/6 ensuring DNS records (apex A + www CNAME, proxied)…"
  ZONE_ID="$($W zone list 2>/dev/null | grep -a -E "\| $DOMAIN " | grep -a -oE '[0-9a-f]{32}' | head -1 || true)"
  if [[ -z "$ZONE_ID" ]]; then
    echo "    WARN: zone '$DOMAIN' not found in this account (nameservers may not be active yet). Skipping DNS; add records manually later."
  else
    have_apex="$($W dns records list --zone "$ZONE_ID" --name "$DOMAIN" 2>/dev/null | grep -a -cE '\| A ' || true)"
    [[ "$have_apex" -eq 0 ]] && $W dns records create --zone "$ZONE_ID" --type A --name "@" --content 192.0.2.1 --proxied >/dev/null && echo "    apex A created (proxied)" || echo "    apex A exists"
    have_www="$($W dns records list --zone "$ZONE_ID" --name "www.$DOMAIN" 2>/dev/null | grep -a -cE '\| CNAME ' || true)"
    [[ "$have_www" -eq 0 ]] && $W dns records create --zone "$ZONE_ID" --type CNAME --name "www" --content "$DOMAIN" --proxied >/dev/null && echo "    www CNAME created (proxied)" || echo "    www CNAME exists"
  fi
else
  echo "==> 5/6 skipped (--skip-dns)"
fi

echo "==> 6/6 smoke test…"
WORKERS_URL="$($W deployments list --config "wrangler.${WORKER}.toml" 2>/dev/null | grep -a -oE 'https://[a-z0-9.-]+\.workers\.dev' | head -1 || true)"
if [[ -n "$WORKERS_URL" ]]; then
  CODE="$(curl -s -o /dev/null -w '%{http_code}' --max-time 30 "$WORKERS_URL/" || echo 000)"
  echo "    $WORKERS_URL -> HTTP $CODE"
else
  echo "    (workers.dev URL not detected; check dashboard)"
fi

echo ""
echo "================ DELIVERY SUMMARY ================"
echo "Site:      https://$DOMAIN  (DNS may take up to a few hours)"
echo "Admin:     https://$DOMAIN/admin  (password set by client)"
echo "Worker:    $WORKER"
echo "D1:        $DB ($DB_ID)"
echo "Config:    wrangler.${WORKER}.toml  (keep for redeploys; never commit)"
if [[ -z "$CHANGELOG_URL" || -z "$DEPLOY_HOOK_URL" ]]; then
  echo "TODO: set missing update vars in wrangler.${WORKER}.toml [vars]:"
  [[ -z "$CHANGELOG_URL" ]] && echo "  UPDATE_CHANGELOG_URL = \"https://<RELEASES_REPO raw>/releases.json (public releases feed)\""
  [[ -z "$DEPLOY_HOOK_URL" ]] && echo "  UPDATE_DEPLOY_HOOK_URL = \"<hosting redeploy hook for $DOMAIN>\""
  echo "  (or re-run with --changelog-url / --deploy-hook-url)"
fi
echo "=================================================="
echo "Tell the client to delete the API token after delivery."
