#!/usr/bin/env bash
# provision-client.sh — one-command sale: create + configure + deploy a buyer site.
#
# Usage:
#   ./scripts/provision-client.sh --slug <slug> --domain <domain> \
#       --admin-password 'S3cret!' [--hosting cloudflare|vercel|vps|shared] \
#       [--cf-token CF_TOKEN] [--org tavana-clients]
#
# What it does:
#   1. Creates org repo from the template (private) + topic tavana-client.
#   2. Sets repo secrets (ADMIN_PASSWORD, SESSION_SECRET, CLOUDFLARE_* if cloudflare).
#   3. Creates D1 (+ note KV) via wrangler when a CF token is available.
#   4. Generates + commits buyer wrangler.toml (per deploy-client.sh conventions).
#   5. Triggers initial deploy (push or workflow_dispatch) and prints a summary.
#
# Notes:
#   - Never commit a token. Pass via --cf-token or CLOUDFLARE_API_TOKEN env.
#   - Bash + gh + node required. Run from the project root.
#   - gheshlaghi.ir is a legacy exception — this script never touches it.
set -euo pipefail

TEMPLATE_REPO="ardijon/insurance-recruit-template"
ORG="tavana-clients"
SLUG=""
DOMAIN=""
ADMIN_PASSWORD=""
HOSTING="cloudflare"
CF_TOKEN="${CLOUDFLARE_API_TOKEN:-}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --slug) SLUG="$2"; shift 2 ;;
    --domain) DOMAIN="$2"; shift 2 ;;
    --admin-password) ADMIN_PASSWORD="$2"; shift 2 ;;
    --hosting) HOSTING="$2"; shift 2 ;;
    --cf-token) CF_TOKEN="$2"; shift 2 ;;
    --org) ORG="$2"; shift 2 ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

[[ -z "$SLUG" ]] && { echo "ERROR: --slug is required (e.g. buyer-ahmadi)." >&2; exit 1; }
[[ -z "$DOMAIN" ]] && { echo "ERROR: --domain is required (e.g. ahmadi.ir)." >&2; exit 1; }
[[ -z "$ADMIN_PASSWORD" ]] && { echo "ERROR: --admin-password is required." >&2; exit 1; }
(( ${#ADMIN_PASSWORD} < 8 )) && { echo "ERROR: admin password must be >= 8 chars." >&2; exit 1; }
case "$HOSTING" in
  cloudflare|vercel|vps|shared) ;;
  *) echo "ERROR: --hosting must be cloudflare|vercel|vps|shared." >&2; exit 1 ;;
esac
[[ "$DOMAIN" == "gheshlaghi.ir" || "$DOMAIN" == "www.gheshlaghi.ir" ]] && { echo "ERROR: gheshlaghi.ir is a legacy exception — refusing to provision." >&2; exit 1; }

REPO="$ORG/$SLUG"
echo "==> 1/5 creating repo $REPO from template…"
gh repo create "$REPO" --template "$TEMPLATE_REPO" --private 2>&1 | tail -2
gh api "repos/$REPO/topics" -X PUT -f 'names[]=tavana-client' --silent
echo "    topic tavana-client added"

echo "==> 2/5 setting repo secrets…"
gh secret set ADMIN_PASSWORD -R "$REPO" --body "$ADMIN_PASSWORD" >/dev/null
SESSION_SECRET="$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")"
gh secret set SESSION_SECRET -R "$REPO" --body "$SESSION_SECRET" >/dev/null
echo "    ADMIN_PASSWORD + SESSION_SECRET set"
if [[ "$HOSTING" == "cloudflare" ]]; then
  if [[ -n "$CF_TOKEN" ]]; then
    export CLOUDFLARE_API_TOKEN="$CF_TOKEN"
    ACCOUNT_ID="$(node ./node_modules/wrangler/bin/wrangler.js whoami 2>/dev/null | grep -a -oE '[0-9a-f]{32}' | head -1 || true)"
    if [[ -n "$ACCOUNT_ID" ]]; then
      gh secret set CLOUDFLARE_API_TOKEN -R "$REPO" --body "$CF_TOKEN" >/dev/null
      gh secret set CLOUDFLARE_ACCOUNT_ID -R "$REPO" --body "$ACCOUNT_ID" >/dev/null
      echo "    CLOUDFLARE_API_TOKEN + CLOUDFLARE_ACCOUNT_ID set"
    else
      echo "    WARN: CF token invalid — skipping CLOUDFLARE_* secrets (set them manually later)."
    fi
  else
    echo "    TODO: set CLOUDFLARE_API_TOKEN + CLOUDFLARE_ACCOUNT_ID on $REPO (no --cf-token given)."
  fi
fi

echo "==> 3/5 provisioning data layer…"
DB_NAME="manager_$(echo "$SLUG" | tr '-' '_')_db"
DB_ID=""
if [[ -n "$CF_TOKEN" && "$HOSTING" == "cloudflare" ]]; then
  export CLOUDFLARE_API_TOKEN="$CF_TOKEN"
  W="node ./node_modules/wrangler/bin/wrangler.js"
  DB_ID="$($W d1 list 2>/dev/null | grep -a -E "\| $DB_NAME " | grep -a -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1 || true)"
  if [[ -z "$DB_ID" ]]; then
    DB_ID="$($W d1 create "$DB_NAME" 2>&1 | grep -a -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1 || true)"
  fi
  [[ -n "$DB_ID" ]] && echo "    D1 $DB_NAME ($DB_ID)" || echo "    TODO: create D1 '$DB_NAME' manually and fill database_id below."
else
  echo "    TODO: create D1 database '$DB_NAME' (needs CF token) and fill database_id below."
fi
DB_ID="${DB_ID:-00000000-0000-0000-0000-000000000000}"

echo "==> 4/5 generating buyer wrangler.toml…"
APP_VERSION="$(node -p "require('./package.json').version")"
WORKER="manager-${SLUG}"
TMPDIR_WORK="$(mktemp -d)"
gh repo clone "$REPO" "$TMPDIR_WORK/$SLUG" -- --quiet 2>/dev/null
cd "$TMPDIR_WORK/$SLUG"
cat > wrangler.toml <<EOF
# Auto-generated by scripts/provision-client.sh for $DOMAIN — buyer repo config.
name = "$WORKER"
main = ".open-next/worker.js"
compatibility_date = "2025-08-16"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
DEMO_MODE = "false"
ADMIN_PASSWORD = "$ADMIN_PASSWORD"
SESSION_SECRET = "$SESSION_SECRET"
APP_VERSION = "$APP_VERSION"
UPDATE_CHANGELOG_URL = "https://raw.githubusercontent.com/tavana-clients/releases/main/releases.json"

[[d1_databases]]
binding = "DB"
database_name = "$DB_NAME"
database_id = "$DB_ID"

[[routes]]
pattern = "$DOMAIN/*"
zone_name = "$DOMAIN"

[[routes]]
pattern = "www.$DOMAIN/*"
zone_name = "$DOMAIN"

[build]
command = "npx @opennextjs/cloudflare build"
EOF
git add wrangler.toml
git -c user.name="provision-bot" -c user.email="bot@users.noreply.github.com" commit -m "provision: buyer config for $DOMAIN" --quiet
git push origin HEAD --quiet
cd - >/dev/null
rm -rf "$TMPDIR_WORK"
echo "    wrangler.toml committed to $REPO"

echo "==> 5/5 triggering initial deploy…"
if [[ "$HOSTING" == "cloudflare" && -n "$CF_TOKEN" ]]; then
  echo "    push to main already triggers .github/workflows/deploy.yml (auto-deploy on push)."
else
  gh workflow run deploy.yml -R "$REPO" 2>/dev/null \
    && echo "    workflow_dispatch sent (deploy.yml)" \
    || echo "    TODO: trigger deploy manually (push to main or run deploy.yml)."
fi

echo ""
echo "================ PROVISION SUMMARY ================"
echo "Repo:      https://github.com/$REPO"
echo "Site:      https://$DOMAIN  (add CNAME $DOMAIN -> workers.dev, or move nameservers; DNS may take hours)"
echo "Admin:     https://$DOMAIN/admin"
echo "Worker:    $WORKER"
echo "D1:        $DB_NAME ($DB_ID)"
case "$HOSTING" in
  cloudflare) echo "TODO: add domain to CF zone + verify CLOUDFLARE_* secrets on $REPO." ;;
  vercel)  echo "TODO (vercel): import $REPO in Vercel dashboard, set ADMIN_PASSWORD/SESSION_SECRET env, add domain $DOMAIN." ;;
  vps)     echo "TODO (vps): on server: git clone $REPO, run scripts/update.sh, point nginx to it, add TLS for $DOMAIN." ;;
  shared)  echo "TODO (shared): npm run build, upload .next + public via FTP/cPanel, set env, bind $DOMAIN." ;;
esac
echo "خلاصه فارسی: ریپوی $SLUG ساخته و پیکربندی شد؛ دیپلوی اولیه آغاز شد. موارد TODO بالا را انجام دهید."
echo "=================================================="
